export const FETCH_AUTHENTICATION = 'FETCH_AUTHENTICATION';
export const FETCH_AUTHENTICATION_SUCCESS = 'FETCH_AUTHENTICATION_SUCCESS';
export const FETCH_AUTHENTICATION_FAILURE = 'FETCH_AUTHENTICATION_FAILURE';
